version: '3.8'

services:
  fastapi:
    build: auth_core
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth_db
      - REDIS_HOST=redis
    # volumes:
    #   - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mongo_data:
